version: '3.8'
services:
  mysql_db3:
    image: mysql:latest
    container_name: mysql_db3
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: usuarios_db
    volumes:
      - ./docker/mysql/usuarios_db_data:/var/lib/mysql
    networks:
      - ali-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  usuariosecurityservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuariosecurityservice
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db3:3306/usuarios_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_SERVER_ADDRESS: 0.0.0.0
      SPRING_SERVER_PORT: 8087
      jpa:
      hibernate:
      ddl-auto: update
      show-sql: true
    depends_on:
      mysql_db3:
        condition: service_healthy
    networks:
      - ali-network

volumes:
  usuarios_db_data:

networks:
  ali-network:
    driver: bridge